# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6a19\u984c')),
                ('content', models.TextField(verbose_name='\u5167\u5bb9')),
            ],
            options={
                'db_table': 'about',
                'verbose_name': '\u95dc\u65bc\u8056\u68ee',
                'verbose_name_plural': '\u95dc\u65bc\u8056\u68ee',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u516c\u53f8\u540d')),
                ('zipcode', models.IntegerField(default=0, verbose_name='\u90f5\u905e\u5340\u865f')),
                ('address', models.CharField(max_length=200, verbose_name='\u5730\u5740')),
            ],
            options={
                'db_table': 'company',
                'verbose_name': '\u516c\u53f8\u8cc7\u8a0a',
                'verbose_name_plural': '\u516c\u53f8\u8cc7\u8a0a',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('email', models.EmailField(max_length=200, verbose_name='\u4fe1\u7bb1')),
                ('url', models.URLField(blank=True, null=True, verbose_name='\u7db2\u5740')),
                ('message', models.TextField(verbose_name='\u8a0a\u606f')),
            ],
            options={
                'db_table': 'contact',
                'verbose_name': '\u806f\u7d61\u6211\u5011',
                'verbose_name_plural': '\u806f\u7d61\u6211\u5011',
            },
        ),
        migrations.CreateModel(
            name='Management_Philosophy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6a19\u984c')),
                ('content', models.TextField(verbose_name='\u5167\u5bb9')),
            ],
            options={
                'db_table': 'management_philosophy',
                'verbose_name': '\u7d93\u71df\u7406\u5ff5',
                'verbose_name_plural': '\u7d93\u71df\u7406\u5ff5',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='./no-profile-pic-img.gif', upload_to='./', verbose_name='\u5716\u793a')),
                ('title', models.CharField(max_length=50, verbose_name='\u6a19\u984c')),
                ('url', models.URLField(verbose_name='\u7db2\u5740')),
            ],
            options={
                'db_table': 'partner',
                'verbose_name': '\u5408\u4f5c\u4f19\u4f34',
                'verbose_name_plural': '\u5408\u4f5c\u4f19\u4f34',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6a19\u984c')),
                ('content', models.CharField(max_length=100, verbose_name='\u5167\u5bb9')),
            ],
            options={
                'db_table': 'slider',
                'verbose_name': '\u9996\u9801\u6ed1\u584a',
                'verbose_name_plural': '\u9996\u9801\u6ed1\u584a',
            },
        ),
    ]
