# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170810_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='GA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=14, verbose_name='追蹤碼ID')),
            ],
            options={
                'db_table': 'ga',
                'verbose_name_plural': 'GA追蹤',
                'verbose_name': 'GA追蹤',
            },
        ),
    ]
